name: Deploy robots txt

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run deploy script
        env:
          SHOPIFY_ADMIN_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
        run: python3 scripts/push_robots_txt.py